site_name: coppaFISH
repo_url: https://github.com/jduffield65/iss_python
repo_name: jduffield65/iss_python

theme:
  name: material
  # 404 page
  static_templates:
      - 404.html
  palette:
    primary: black
  # Necessary for search to work properly
  include_search_page: false
  search_index_only: true

  # Default values, taken from mkdocs_theme.yml
  language: en
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.indexes
    - navigation.expand
    - content.tabs.link
    - navigation.sections
    # - toc.integrate  # This puts table of contents in right sidebar into left sidebar but makes left sidebar quite big
    - navigation.top
  font:
      text: Roboto
      code: Roboto Mono
  favicon: images/logo.png
  logo: images/logo.png
  icon:
      logo: logo

plugins:
  - search
  - mkdocstrings:
        default_handler: python
        handlers:
            python:
                rendering:
                    show_root_toc_entry: false # stops extra heading in contents of Code pages

extra:
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/jduffield65/iss_python
      name: Github Repository

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - tables
  - attr_list
  - md_in_html
  - def_list
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

nav:
    - Home: index.md
    - Getting Started:
        - Setting up the Config File: config_setup.md
        - Running the code: run_code.md
        - Viewing the results: view_results.md
        - Notebook: notebook.md
        - Config Default Settings: config.md
        - Notebook Comments: notebook_comments.md
    - Pipeline:
        - Extract and Filter: pipeline/extract.md
        - Find Spots: pipeline/find_spots.md
        - Stitch: pipeline/stitch.md
    - Code:
        - Setup:
            - Notebook: code/setup/notebook.md
            - Tile Detail: code/setup/tile_details.md
            - File Names: code/setup/file_names.md
        - Extract:
            - Base: code/extract/base.md
            - Deconvolution: code/extract/deconvolution.md
            - Fstack: code/extract/fstack.md
            - Scale: code/extract/scale.md
        - Find Spots:
            - Base: code/find_spots/base.md
            - Detect: code/find_spots/detect.md
        - Stitch:
            - Shift: code/stitch/shift.md
            - Starting Shifts: code/stitch/starting_shifts.md
            - Tile Origin: code/stitch/tile_origin.md
        - Point Cloud Registration:
            - Base: code/pcr/base.md
        - Spot Colors:
            - Base: code/spot_colors/base.md
        - Call Spots:
            - Base: code/call_spots/base.md
            - Background: code/call_spots/background.md
            - Bleed Matrix: code/call_spots/bleed_matrix.md
            - Dot Product: code/call_spots/dot_product.md
            - Quality Check: code/call_spots/qual_check.md
        - OMP:
            - Coefficients: code/omp/coefs.md
            - Spots: code/omp/spots.md
        - Pipeline:
            - Run: code/pipeline/run.md
            - Basic Info: code/pipeline/basic_info.md
            - Extract: code/pipeline/extract_run.md
            - Find Spots: code/pipeline/find_spots.md
            - Stitch: code/pipeline/stitch.md
            - Register Initial: code/pipeline/register_initial.md
            - Register: code/pipeline/register.md
            - Get Reference Spots: code/pipeline/get_reference_spots.md
            - Call Reference Spots: code/pipeline/call_reference_spots.md
            - OMP: code/pipeline/omp.md
        - Utils:
            - Base: code/utils/base.md
            - Errors: code/utils/errors.md
            - pciSeq: code/utils/pciseq.md
            - Matlab: code/utils/matlab.md
            - Morphology: code/utils/morphology.md
            - nd2: code/utils/nd2.md
            - npy: code/utils/npy.md
            - Strel: code/utils/strel.md
        - Plot:
            - Viewer: code/plot/viewer.md
            - Raw: code/plot/raw.md
            - Extract: code/plot/extract.md
            - Find Spots: code/plot/find_spots.md
            - Stitch: code/plot/stitch.md
            - Register: code/plot/register.md
            - Call Spots: code/plot/call_spots.md
            - OMP: code/plot/omp.md
        - Separate Round Registration:
            - code/sep_round_reg.md